# Generated by Django 5.0.7 on 2024-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ramjeet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='cost_per_item',
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
       
      
    ]
