# Generated by Django 5.0.7 on 2024-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0002_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
