# Generated by Django 5.0.7 on 2024-07-28 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0002_rename_inverdinvoiceproductiondetail_inverdinvoiceproductdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmaster',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Add Brand'},
        ),
        migrations.AlterModelOptions(
            name='firmmaster',
            options={'verbose_name': 'Firm', 'verbose_name_plural': 'Add Firm'},
        ),
        migrations.AlterModelOptions(
            name='inventorymaster',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Add Stock'},
        ),
        migrations.AlterModelOptions(
            name='itemmaster',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Add Item'},
        ),
        migrations.AlterModelOptions(
            name='unitmaster',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Add Stock'},
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField()),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramjeet.itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramjeet.itemmaster')),
            ],
        ),
    ]
