# Generated by Django 5.0.7 on 2024-10-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ramjeet', '0002_remove_itemmaster_cost_per_item_and_more'),
    ]

    operations = [
       
    ]
