# Generated by Django 5.0.7 on 2024-07-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0003_alter_brandmaster_options_alter_firmmaster_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='item',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
