# Generated by Django 5.0.7 on 2024-10-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ramjeet', '0003_myuser_full_name_myuser_groups_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
