# Generated by Django 5.0.7 on 2024-08-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0004_remove_sales_item_delete_purchases_delete_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmaster',
            options={},
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='image',
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ramjeet.itemmaster')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Add Item',
            },
        ),
    ]
