# Generated by Django 5.0.7 on 2024-11-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0006_deliveryaddress_ordermaster_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='delivery_address',
        ),
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramjeet.deliveryaddress'),
        ),
    ]
