# Generated by Django 5.0.7 on 2024-10-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ramjeet', '0006_inventorymaster_margin_inventorymaster_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='profit',
        ),
      
    ]
