# Generated by Django 5.0.7 on 2024-09-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0008_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
