# Generated by Django 5.0.7 on 2024-10-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0008_myuser_full_name_myuser_groups_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ramjeet.brandmaster'),
        ),
    ]
