# Generated by Django 5.0.7 on 2024-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0009_remove_deliverymaster_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
