# Generated by Django 5.0.7 on 2024-11-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0010_alter_deliverymaster_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymaster',
            name='delivery_status',
        ),
    ]
