# Generated by Django 5.0.7 on 2024-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0011_remove_deliverymaster_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymaster',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
