# Generated by Django 5.0.7 on 2024-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramjeet', '0013_remove_ordermaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymaster',
            name='canceled_at',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverymaster',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=50),
        ),
    ]
